version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: mendeit/kittygram_backend
    container_name: backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/var/www/kittygram/media/
    depends_on:
      - db

  frontend:
    image: mendeit/kittygram_frontend
    container_name: frontend
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

  gateway:
    image: mendeit/kittygram_gateway
    container_name: gateway
    volumes:
      - static:/staticfiles/
      - media:/var/www/kittygram/media/
    ports:
      - 9000:80
