version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: kittygram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/mediafiles/
    depends_on:
      - db

  frontend:
    build: ./frontend/
    image: mendeit/kittygram_backend
    container_name: kittygram_backend
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

  gateway:
    build: ./nginx/
    image: mendeit/kittygram_gateway
    container_name: kittygram_gateway
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    ports:
      - 9000:80
